apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector:
    app: {{ .Release.Name }}-{{ .Chart.AppVersion }}
  ports:
    - port: {{ .Values.Service.port }}
      targetPort: {{ .Values.Service.port }}
  type: {{ .Values.Service.type }}
